import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { Navbar } from '@/components/navbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
const inter = Inter({ subsets: ['latin'], weight: ['400', '700'] });

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body className={`${inter.className}`}>
                <Navbar
                    user={{
                        username: 'Lucas',
                        email: 'jj@gmail.com',
                        ID_USUARIO: 1,
                        senha: '123456'
                    }}
                    isAdmin={true}
                />
                {children}
                <Toaster />
            </body>
        </html>
    );
}
